'use client';

import { motion } from 'framer-motion';
import { AlertTriangle, Bell, Camera, Check, CheckCircle2, ChevronRight, Eye, EyeOff, Github, Globe2, Loader2, LockKeyhole, LogOut, Mail, Search, ShieldAlert, ShieldCheck, Trash2, UserRound, XCircle } from 'lucide-react';
import { useState } from 'react';
import { authRoles, countries, devices, notifications, onboardingSteps, profile, recentSearches, roleDescriptions, settingsSections } from '@/lib/auth-data';

type FieldProps = { label: string; type?: string; placeholder: string; state?: 'error'|'success'|'loading'; disabled?: boolean; hint?: string; };
const fade = { initial:{ opacity:0, y:18 }, animate:{ opacity:1, y:0 }, transition:{ duration:.45 } };

export function AuthLayout({ children, eyebrow='Secure access', title, subtitle }: { children: React.ReactNode; eyebrow?: string; title: string; subtitle: string }) {
  return <main className="premium-grid min-h-screen px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto grid min-h-[calc(100vh-3rem)] w-full max-w-6xl items-center gap-6 lg:grid-cols-[.9fr_1.1fr]"><motion.section {...fade} className="glass rounded-[2rem] p-6 sm:p-8"><div className="mb-8 inline-flex rounded-full border border-aqua/30 bg-aqua/10 px-4 py-2 text-xs font-bold uppercase tracking-[.2em] text-aqua">{eyebrow}</div><h1 className="text-4xl font-black tracking-tight sm:text-6xl">{title}</h1><p className="mt-5 max-w-xl text-base leading-8 text-white/65">{subtitle}</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{['Supabase-ready','RBAC UI','Mobile first'].map(x=><span key={x} className="rounded-2xl bg-white/8 p-4 text-sm text-white/70">{x}</span>)}</div></motion.section><AuthCard>{children}</AuthCard></div></main>;
}
export function AuthCard({ children }: { children: React.ReactNode }) { return <motion.section {...fade} transition={{duration:.55, delay:.08}} className="glass rounded-[2rem] p-5 shadow-2xl sm:p-7">{children}</motion.section>; }
export function AuthInput(p: FieldProps) { const [show,setShow]=useState(false); const password=p.type==='password'; const type=password && show?'text':p.type||'text'; return <label className="block space-y-2"><span className="text-sm font-semibold text-white/75">{p.label}</span><div className={`flex items-center gap-2 rounded-2xl border bg-white/5 px-4 py-3 ${p.state==='error'?'border-red-400/70':p.state==='success'?'border-emerald-400/70':'border-white/10'} ${p.disabled?'opacity-50':''}`}><input disabled={p.disabled} type={type} placeholder={p.placeholder} className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-white/35" aria-invalid={p.state==='error'} />{p.state==='loading' && <Loader2 className="animate-spin text-aqua" size={18}/>} {p.state==='success' && <Check className="text-emerald-300" size={18}/>} {password && <button type="button" aria-label="Toggle password visibility" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button>}</div>{p.hint && <p className={`text-xs ${p.state==='error'?'text-red-300':'text-white/45'}`}>{p.hint}</p>}</label> }
export function AuthForm({ mode }: { mode: 'login'|'register'|'forgot'|'reset' }) { return <form className="space-y-4"><AuthInput label="Email" type="email" placeholder="operations@alphaweber.com" state="success" hint="Validation placeholder: business email format." />{mode==='register' && <><AuthInput label="Full name" placeholder="Alpha Weber Operations Lead"/><AuthInput label="Company name" placeholder="Alpha Weber"/><div className="grid gap-4 sm:grid-cols-2"><AuthInput label="Phone number" placeholder="+1 (415) 555-0187"/><label className="block space-y-2"><span className="text-sm font-semibold text-white/75">Country</span><select className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm outline-none">{countries.map(c=><option className="bg-slate-950" key={c}>{c}</option>)}</select></label></div></>}{mode!=='forgot' && <AuthInput label="Password" type="password" placeholder="Minimum 12 characters" state={mode==='reset'?'loading':undefined} hint="Validation placeholder: uppercase, number, symbol, and 12+ characters." />}{(mode==='register'||mode==='reset') && <><AuthInput label="Confirm password" type="password" placeholder="Re-enter password" state="error" hint="Passwords must match before submission."/><PasswordStrength/><PasswordRequirements/></>}{mode==='register' && <AuthInput label="Referral code (optional)" placeholder="PARTNER-ALPHA" disabled/>}<div className="flex flex-wrap items-center justify-between gap-3 text-sm text-white/60"><label className="flex items-center gap-2"><input type="checkbox"/> {mode==='register'?'Accept terms':'Remember me'}</label><span className="text-aqua">Future Supabase Auth action</span></div><button className="w-full rounded-2xl bg-aqua px-5 py-4 font-black text-obsidian shadow-glow">Continue securely</button><SocialLoginButtons/></form> }
export function PasswordStrength(){ return <div><div className="mb-2 flex justify-between text-xs"><span>Password strength</span><span className="text-gold">Strong-ready</span></div><div className="grid grid-cols-4 gap-2">{[1,2,3,4].map(i=><div key={i} className={`h-2 rounded-full ${i<4?'bg-aqua':'bg-white/15'}`}/>)}</div></div> }
export function PasswordRequirements(){ return <ul className="grid gap-2 text-xs text-white/55 sm:grid-cols-2">{['12+ characters','Uppercase letter','Number included','Special symbol'].map(x=><li key={x} className="flex items-center gap-2"><CheckCircle2 size={14} className="text-aqua"/>{x}</li>)}</ul> }
export function SocialLoginButtons(){ return <div className="grid gap-3 sm:grid-cols-2"><button type="button" className="rounded-2xl border border-white/10 px-4 py-3 text-sm"><Github className="mr-2 inline" size={16}/>GitHub</button><button type="button" className="rounded-2xl border border-white/10 px-4 py-3 text-sm"><Mail className="mr-2 inline" size={16}/>Google</button></div> }
export function OTPInput(){ return <div className="flex gap-2">{Array.from({length:6}).map((_,i)=><input key={i} maxLength={1} className="h-12 w-full rounded-2xl border border-white/10 bg-white/5 text-center text-lg font-bold outline-none focus:border-aqua" aria-label={`Verification digit ${i+1}`}/>)}</div> }
export function StatusScreen({ type }: { type: 'email'|'success'|'locked'|'expired'|'401'|'403' }) { const map={email:['Check your email','We sent a secure verification link and OTP code to operations@alphaweber.com.',Mail],success:['Setup step completed','Your authentication flow is ready for future backend integration.',CheckCircle2],locked:['Account locked','Too many attempts were detected. Show recovery and support options.',ShieldAlert],expired:['Session expired','Please sign in again to protect workspace data.',AlertTriangle],'401':['Unauthorized','Sign in with a verified account to continue.',XCircle],'403':['Forbidden','Your current role does not include permission for this area.',LockKeyhole]} as const; const [t,s,I]=map[type]; return <AuthLayout title={t} subtitle={s}><div className="space-y-5 text-center"><I className="mx-auto text-aqua" size={52}/><StateStrip/><button className="rounded-2xl bg-aqua px-6 py-4 font-bold text-obsidian">Return to secure sign in</button></div></AuthLayout> }
function StateStrip(){ return <div className="grid grid-cols-2 gap-3 text-xs sm:grid-cols-5">{['Loading','Empty','Success','Error','Disabled'].map(x=><span className="rounded-xl bg-white/8 p-3" key={x}>{x}</span>)}</div> }
export function ProfileSettings(){ return <main className="premium-grid min-h-screen px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6"><TopBar/><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><ProfileCard/><section className="space-y-5"><SettingsNavigation/><InfoGrid/><SecurityPanel/><RoleSystem/><NotificationCenter/><GlobalSearch/><Onboarding/></section></div></div></main> }
function TopBar(){return <div className="glass flex flex-col gap-4 rounded-[2rem] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-aqua">User Management</p><h1 className="text-3xl font-black">Profile, account settings, roles, and notifications</h1></div><UserDropdown/></div>}
function UserDropdown(){return <button className="flex items-center gap-3 rounded-2xl bg-white/8 px-4 py-3"><UserRound/> {profile.name}<ChevronRight size={16}/></button>}
function ProfileCard(){return <aside className="glass h-fit rounded-[2rem] p-6"><div className="relative mx-auto mb-5 grid size-28 place-items-center rounded-[2rem] bg-aqua text-3xl font-black text-obsidian">AW<button className="absolute -bottom-2 -right-2 rounded-full bg-gold p-3 text-obsidian" aria-label="Upload avatar"><Camera size={18}/></button></div><h2 className="text-center text-2xl font-black">{profile.name}</h2><p className="text-center text-white/55">{profile.email}</p><div className="mt-6 space-y-3">{Object.entries(profile).slice(2).map(([k,v])=><div className="rounded-2xl bg-white/8 p-3" key={k}><p className="text-xs uppercase text-white/35">{k}</p><p className="text-sm">{v}</p></div>)}</div></aside>}
function SettingsNavigation(){return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{settingsSections.map(s=>{const I=s.icon;return <article className="glass rounded-3xl p-4" key={s.title}><I className="mb-3 text-aqua"/><h3 className="font-bold">{s.title}</h3><p className="text-xs leading-5 text-white/55">{s.text}</p></article>})}</div>}
function InfoGrid(){return <section className="glass rounded-[2rem] p-5"><h2 className="mb-4 text-xl font-black">Edit profile and company information</h2><div className="grid gap-4 sm:grid-cols-2"><AuthInput label="Full name" placeholder={profile.name}/><AuthInput label="Company name" placeholder={profile.company}/><AuthInput label="Timezone" placeholder={profile.timezone}/><AuthInput label="Language" placeholder={profile.language}/><AuthInput label="Theme preference" placeholder={profile.theme}/><AuthInput label="Notification preference" placeholder={profile.notifications}/></div></section>}
function SecurityPanel(){return <section className="glass rounded-[2rem] p-5"><h2 className="text-xl font-black">Security, sessions, and account actions</h2><div className="mt-4 grid gap-4 lg:grid-cols-3"><AccountCard title="Password change" icon={<LockKeyhole/>}/><AccountCard title="Deactivate account" icon={<LogOut/>}/><AccountCard title="Delete account" icon={<Trash2/>} danger/></div><div className="mt-4 grid gap-3">{devices.map(d=>{const I=d.icon;return <div className="flex items-center justify-between rounded-2xl bg-white/8 p-4" key={d.name}><span className="flex items-center gap-3"><I className="text-gold"/>{d.name} · {d.location}</span><span className="text-xs text-aqua">{d.seen}</span></div>})}</div></section>}
function AccountCard({title,icon,danger}:{title:string;icon:React.ReactNode;danger?:boolean}){return <div className={`rounded-3xl border p-4 ${danger?'border-red-400/30 bg-red-400/10':'border-white/10 bg-white/8'}`}>{icon}<p className="mt-3 font-bold">{title}</p><p className="text-xs text-white/50">Confirmation dialog and disabled/loading states prepared.</p></div>}
function RoleSystem(){return <section className="glass rounded-[2rem] p-5"><h2 className="mb-4 text-xl font-black">Role system</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{authRoles.map(r=><article className="rounded-3xl bg-white/8 p-4" key={r}><span className="rounded-full bg-aqua/10 px-3 py-1 text-xs text-aqua">{r}</span><p className="mt-3 text-xs text-white/55">{roleDescriptions[r as keyof typeof roleDescriptions]}</p></article>)}</div></section>}
function NotificationCenter(){return <section className="glass rounded-[2rem] p-5"><h2 className="mb-4 flex items-center gap-3 text-xl font-black"><Bell/> Notification center <span className="rounded-full bg-gold px-2 text-xs text-obsidian">2 unread</span></h2>{notifications.map(n=><div className="mb-3 rounded-2xl bg-white/8 p-4" key={n.title}><p className="font-bold">{n.title} {n.unread && <span className="text-aqua">•</span>}</p><p className="text-sm text-white/55">{n.text}</p></div>)}<p className="rounded-2xl border border-dashed border-white/15 p-4 text-sm text-white/45">Empty state: no notifications require attention.</p></section>}
function GlobalSearch(){return <section className="glass rounded-[2rem] p-5"><h2 className="mb-4 text-xl font-black">Global search</h2><div className="flex gap-3 rounded-2xl bg-white/8 p-4"><Search className="text-aqua"/><input className="flex-1 bg-transparent outline-none" placeholder="Search settings, roles, sessions..."/></div><div className="mt-4 flex flex-wrap gap-2">{recentSearches.map(s=><span className="rounded-full bg-white/8 px-3 py-2 text-xs" key={s}>{s}</span>)}</div><p className="mt-3 text-sm text-white/45">Empty search state appears when no matching settings are found.</p></section>}
function Onboarding(){return <section className="glass rounded-[2rem] p-5"><h2 className="mb-4 text-xl font-black">Onboarding</h2><div className="grid gap-3 sm:grid-cols-2">{onboardingSteps.map(s=>{const I=s.icon;return <article className="rounded-3xl bg-white/8 p-4" key={s.title}><I className="mb-3 text-aqua"/><h3 className="font-bold">{s.title}</h3><p className="text-xs leading-5 text-white/55">{s.text}</p></article>})}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><AuthInput label="Business category" placeholder="B2B growth services"/><AuthInput label="Logo upload" placeholder="Upload PNG or SVG" state="loading"/></div></section>}
